### PR TITLE
Update ar.json

### PR DESCRIPTION
**Pull request by agharbeia**
Completing the Arabic translation, and a slight fix in one string of the three that were originally there.
The translation has been tested in a working wiki, so all contextual ambiguities should be resolved now.

### CODE REVIEW

**Comment by jdforrester** [comment]
Hello! Thank you for your work, but this is a read-only copy of the repo. Translations for our software are managed on https://translatewiki.net/ where you can get an account and provide these.

**Comment by agharbeia** [comment]
I already looked in TW but couldn't find translation for EditAccount! I even tried following the link from https://mediawiki.org/wiki/Extension:EditAccount

Not to mention that TW is not intuitive at all and inefficient to work with.

Anyhow, I just wanted to keep a log/diff of the localisation that we intent to use for our own projects using MW and its extensions, since it unlikely that my translations will be accepted by those who preside over Arabic Wikipedia. So it's fine.

Thanks.

**Comment by Nikerabbit** [comment]
FYI, this is in translatewiki.net configuration:
```
# Incomplete message documentation file - 2014-11-20
#Edit Account
```

Message documentation is still incomplete. In any case this is read-only copy like already mentioned.

**Comment by nemobis** [comment]
If you already translated the messages I guess you understood what they 
do/where they're used, so you could send a patch adding documentation to 
qqq.json.
https://www.mediawiki.org/wiki/Localisation#Message_documentation

See how to send patches https://www.mediawiki.org/wiki/Gerrit/Tutorial

**Comment by jdforrester** [comment]
Moved to gerrit in https://gerrit.wikimedia.org/r/#/c/305548/ for simplicity

**Pull request closed without merging**
